### ISSUE TITLE
How to build module EtherCIS?

### ISSUE THREAD

**Issue by maxcda101** [RippleOSI/Qewd-Ripple#27]
Hi guy.
I have problem in deploying RippleOSI.
Module ethercis, what version are you using?
I retried new version of ethercis (https://github.com/ethercis), but not working.
Are you have document for deploying module ethercis?
Regards.

**Comment by tony-shannon** [comment]
thanks

You'll need to provide more details on what you are trying to do & as to
where you are getting stuck.

QEWD-Ripple sets up the Ripple showcase stack with automatic links to a
cloud based EtherCIS instance.
Are you trying to set your own instance of EtherCIS up?
If so you'll need to post your issue on the etherCIS github..

Tony

**Comment by maxcda101** [comment]
Thank you! I installed ethercis to local.
I see source openEHR has 2 server "marand" and "ethercis".
When to use "marand" or "ethercis"?
Thanks.

**Comment by tony-shannon** [comment]
Marand offer a commercial enterprise grade openEHR repository.
http://www.marand.com/
For OS projects, just use EtherCIS
