### ISSUE TITLE
Version 2.21.1 Consume a lot of resources

### ISSUE THREAD

**Issue by maxcda101** [RippleOSI/Qewd-Ripple#29]
Hi Ripple team
I updated qewd-ripple to version 2.21.1, then system consume a lot of resources
Are you like this picture?
![capture](https://cloud.githubusercontent.com/assets/11785724/26307296/08b8d0f0-3f1e-11e7-8fdb-82b894a610cd.PNG)
Thanks

**Comment by tony-shannon** [comment]
Thanks @maxcda101 
Had you noticed a difference resource usage picture in earlier version?
@robtweed , thanks for your view on this..
Tony

**Comment by maxcda101** [comment]
I checked versions, then starting at version 2.18 is resource consuming and this is log of qewd-ripple.
![capture](https://cloud.githubusercontent.com/assets/11785724/26336198/87d249ca-3f9b-11e7-927f-df4e8cf0e310.PNG)

This is resource of version 2.17.1

![capture2](https://cloud.githubusercontent.com/assets/11785724/26336280/d73921fa-3f9b-11e7-81a1-e4e7c158b02f.PNG)

Quan from ThinkLaps-Vn

**Comment by robtweed** [comment]
My guess is that something has crashed. Stop the QEWD master process, restart and then look at the console log / error log - eg if you're running qewd-ripple using PM2, look in ~/.pm2/logs/ and you should find a file named something like qewd-demo-error-0.log.  See what error(s) it reports

**Comment by robtweed** [comment]
Just tested a fresh build using the latest installer for GT.M.  Installed cleanly, Ripple runs without errors and CPU is negligible.

**Comment by robtweed** [comment]
OK I see a problem with Redis - let me sort it out

**Comment by robtweed** [comment]
OK I've fixed the Redis problem, and also an nginx-related configuration issue.  Try running a fresh install on a  new VM using the Redis installer.  Thanks for flagging up the problem!

**Comment by maxcda101** [comment]
Thanks @robtweed 
If i reinstall on old VM, any problems? Or uou give me the script to fix.

**Comment by robtweed** [comment]
If you're going to patch it on your current VM, I think you'll need to do the following:

# stop your QEWD processes
pm2 stop ripple-demo
pm2 stop ripple-secure

# re-install qewd-ripple and its dependencies
cd ~/qewd
npm uninstall qewd-ripple
npm install qewd-ripple

# patch up the nginx environment
sudo ln -s ~/qewd/ssl/ /var/ssl
sudo systemctl restart nginx

# start your QEWD processes
pm2 start ripple-demo
pm2 start ripple-secure

# Check the PM2 status:
 pm2 status

It should show ripple-demo and ripple-secure running

Point your browser at your VM's IP address, eg

http://192.168.1.123

The RippleOSI UI (PulseTile) should fire up

Let me know if you still see any problems

**Comment by maxcda101** [comment]
I was successful and no problem anymore.
Thank you very much for your help
Quan from ThinkLabs-Vn
