### ISSUE TITLE
Install script needs to reflect new PulseTile Path

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/Qewd-Ripple#6]
Installer script needs minor amend to reflect new UI codebase (PulseTile) Path

change from
wget https://github.com/RippleOSI/Org-Ripple-UI-rf3/raw/develop/build/ripple_latest.zip
to
wget https://github.com/PulseTile/PulseTile/blob/master/build/ripple-latest.zip

**Comment by chrisjohnson1988** [comment]
Presumable this should be in reference to the **raw** file: 

    https://github.com/PulseTile/PulseTile/raw/master/build/ripple-latest.zip

Also, the previous link referred to the *develop* branch where as the new link uses the *master* branch. Is this deliberate?

**Comment by tony-shannon** [comment]
good points, thanks Chris

Yes should be the raw file
Should be pointing to master branch also

We need to update this install script, @robtweed will tackle this in due course
thanks again
T

**Comment by tony-shannon** [comment]
this has since been actioned by @robtweed
